export const CARD_LIST_REQUEST = "CARD_LIST_REQUEST";
export const CARD_LIST_SUCCESS = "CARD_LIST_SUCCESS";
export const CARD_LIST_FAIL = "CARD_LIST_FAIL";

export const CARD_LIST_FEW_REQUEST = "CARD_LIST_FEW_REQUEST";
export const CARD_LIST_FEW_SUCCESS = "CARD_LIST_FEW_SUCCESS";
export const CARD_LIST_FEW_FAIL = "CARD_LIST_FEW_FAIL";

export const CARD_DETAILS_REQUEST = "CARD_DETAILS_REQUEST";
export const CARD_DETAILS_SUCCESS = "CARD_DETAILS_SUCCESS";
export const CARD_DETAILS_FAIL = "CARD_DETAILS_FAIL";

export const CARD_DELETE_REQUEST = "CARD_DELETE_REQUEST";
export const CARD_DELETE_SUCCESS = "CARD_DELETE_SUCCESS";
export const CARD_DELETE_FAIL = "CARD_DELETE_FAIL";

export const CARD_CREATE_REQUEST = "CARD_CREATE_REQUEST";
export const CARD_CREATE_SUCCESS = "CARD_CREATE_SUCCESS";
export const CARD_CREATE_FAIL = "CARD_CREATE_FAIL";
export const CARD_CREATE_RESET = "CARD_CREATE_RESET";

export const CARD_UPDATE_REQUEST = "CARD_UPDATE_REQUEST";
export const CARD_UPDATE_SUCCESS = "CARD_UPDATE_SUCCESS";
export const CARD_UPDATE_FAIL = "CARD_UPDATE_FAIL";
export const CARD_UPDATE_RESET = "CARD_UPDATE_RESET";

export const CARD_ITEM_DELIVER_REQUEST = "CARD_ITEM_DELIVER_REQUEST";
export const CARD_ITEM_DELIVER_SUCCESS = "CARD_ITEM_DELIVER_SUCCESS";
export const CARD_ITEM_DELIVER_FAIL = "CARD_ITEM_DELIVER_FAIL";

export const CARD_ADD_ITEM_REQUEST = "CARD_ADD_ITEM_REQUEST";
export const CARD_ADD_ITEM_SUCCESS = "CARD_ADD_ITEM_SUCCESS";
export const CARD_ADD_ITEM_FAIL = "CARD_ADD_ITEM_FAIL";