export const CARD_ORDER_CREATE_REQUEST = 'CARD_ORDER_CREATE_REQUEST'
export const CARD_ORDER_CREATE_SUCCESS = 'CARD_ORDER_CREATE_SUCCESS'
export const CARD_ORDER_CREATE_FAIL = 'CARD_ORDER_CREATE_FAIL'
export const CARD_ORDER_CREATE_RESET = 'CARD_ORDER_CREATE_RESET'

export const CARD_ORDER_DETAILS_REQUEST = 'CARD_ORDER_DETAILS_REQUEST'
export const CARD_ORDER_DETAILS_SUCCESS = 'CARD_ORDER_DETAILS_SUCCESS'
export const CARD_ORDER_DETAILS_FAIL = 'CARD_ORDER_DETAILS_FAIL'

export const CARD_ORDER_PAY_REQUEST = 'CARD_ORDER_PAY_REQUEST'
export const CARD_ORDER_PAY_SUCCESS = 'CARD_ORDER_PAY_SUCCESS'
export const CARD_ORDER_PAY_FAIL = 'CARD_ORDER_PAY_FAIL'
export const CARD_ORDER_PAY_RESET = 'CARD_ORDER_PAY_RESET'

export const CARD_ORDER_LIST_MY_REQUEST = 'CARD_ORDER_LIST_MY_REQUEST'
export const CARD_ORDER_LIST_MY_SUCCESS = 'CARD_ORDER_LIST_MY_SUCCESS'
export const CARD_ORDER_LIST_MY_FAIL = 'CARD_ORDER_LIST_MY_FAIL'
export const CARD_ORDER_LIST_MY_RESET = 'CARD_ORDER_LIST_MY_RESET'

export const CARD_ORDER_UPDATE_REQUEST = 'CARD_ORDER_UPDATE_REQUEST'
export const CARD_ORDER_UPDATE_SUCCESS = 'CARD_ORDER_UPDATE_SUCCESS'
export const CARD_ORDER_UPDATE_FAIL = 'CARD_ORDER_UPDATE_FAIL'

export const CARD_ORDER_LIST_REQUEST = 'CARD_ORDER_LIST_REQUEST'
export const CARD_ORDER_LIST_SUCCESS = 'CARD_ORDER_LIST_SUCCESS'
export const CARD_ORDER_LIST_FAIL = 'CARD_ORDER_LIST_FAIL'