export const COCI_LIST_REQUEST = "COCI_LIST_REQUEST";
export const COCI_LIST_SUCCESS = "COCI_LIST_SUCCESS";
export const COCI_LIST_FAIL = "COCI_LIST_FAIL";

export const COCI_LIST_MY_REQUEST = "COCI_LIST_REQUEST";
export const COCI_LIST_MY_SUCCESS = "COCI_LIST_SUCCESS";
export const COCI_LIST_MY_FAIL = "COCI_LIST_FAIL";

export const COCI_DETAILS_REQUEST = "COCI_DETAILS_REQUEST";
export const COCI_DETAILS_SUCCESS = "COCI_DETAILS_SUCCESS";
export const COCI_DETAILS_FAIL = "COCI_DETAILS_FAIL";

export const COCI_DELETE_REQUEST = "COCI_DELETE_REQUEST";
export const COCI_DELETE_SUCCESS = "COCI_DELETE_SUCCESS";
export const COCI_DELETE_FAIL = "COCI_DELETE_FAIL";

export const COCI_CREATE_REQUEST = "COCI_CREATE_REQUEST";
export const COCI_CREATE_SUCCESS = "COCI_CREATE_SUCCESS";
export const COCI_CREATE_FAIL = "COCI_CREATE_FAIL";

export const COCI_UPDATE_REQUEST = "COCI_UPDATE_REQUEST";
export const COCI_UPDATE_SUCCESS = "COCI_UPDATE_SUCCESS";
export const COCI_UPDATE_FAIL = "COCI_UPDATE_FAIL";

export const COCI_ITEM_DELIVER_REQUEST = "COCI_ITEM_DELIVER_REQUEST";
export const COCI_ITEM_DELIVER_SUCCESS = "COCI_ITEM_DELIVER_SUCCESS";
export const COCI_ITEM_DELIVER_FAIL = "COCI_ITEM_DELIVER_FAIL";