export const JAMB_PASSWORD_RESET_LIST_REQUEST = "JAMB_PASSWORD_RESET_LIST_REQUEST";
export const JAMB_PASSWORD_RESET_LIST_SUCCESS = "JAMB_PASSWORD_RESET_LIST_SUCCESS";
export const JAMB_PASSWORD_RESET_LIST_FAIL = "JAMB_PASSWORD_RESET_LIST_FAIL";

export const JAMB_PASSWORD_RESET_LIST_MY_REQUEST = "JAMB_PASSWORD_RESET_LIST_REQUEST";
export const JAMB_PASSWORD_RESET_LIST_MY_SUCCESS = "JAMB_PASSWORD_RESET_LIST_SUCCESS";
export const JAMB_PASSWORD_RESET_LIST_MY_FAIL = "JAMB_PASSWORD_RESET_LIST_FAIL";

export const JAMB_PASSWORD_RESET_DETAILS_REQUEST = "JAMB_PASSWORD_RESET_DETAILS_REQUEST";
export const JAMB_PASSWORD_RESET_DETAILS_SUCCESS = "JAMB_PASSWORD_RESET_DETAILS_SUCCESS";
export const JAMB_PASSWORD_RESET_DETAILS_FAIL = "JAMB_PASSWORD_RESET_DETAILS_FAIL";

export const JAMB_PASSWORD_RESET_DELETE_REQUEST = "JAMB_PASSWORD_RESET_DELETE_REQUEST";
export const JAMB_PASSWORD_RESET_DELETE_SUCCESS = "JAMB_PASSWORD_RESET_DELETE_SUCCESS";
export const JAMB_PASSWORD_RESET_DELETE_FAIL = "JAMB_PASSWORD_RESET_DELETE_FAIL";

export const JAMB_PASSWORD_RESET_CREATE_REQUEST = "JAMB_PASSWORD_RESET_CREATE_REQUEST";
export const JAMB_PASSWORD_RESET_CREATE_SUCCESS = "JAMB_PASSWORD_RESET_CREATE_SUCCESS";
export const JAMB_PASSWORD_RESET_CREATE_FAIL = "JAMB_PASSWORD_RESET_CREATE_FAIL";
export const JAMB_PASSWORD_RESET_CREATE_RESET = "JAMB_PASSWORD_RESET_CREATE_RESET";

export const JAMB_PASSWORD_RESET_UPDATE_REQUEST = "JAMB_PASSWORD_RESET_UPDATE_REQUEST";
export const JAMB_PASSWORD_RESET_UPDATE_SUCCESS = "JAMB_PASSWORD_RESET_UPDATE_SUCCESS";
export const JAMB_PASSWORD_RESET_UPDATE_FAIL = "JAMB_PASSWORD_RESET_UPDATE_FAIL";
