export const OLEVEL_UPLOAD_LIST_REQUEST = "OLEVEL_UPLOAD_LIST_REQUEST";
export const OLEVEL_UPLOAD_LIST_SUCCESS = "OLEVEL_UPLOAD_LIST_SUCCESS";
export const OLEVEL_UPLOAD_LIST_FAIL = "OLEVEL_UPLOAD_LIST_FAIL";

export const OLEVEL_UPLOAD_LIST_MY_REQUEST = "OLEVEL_UPLOAD_LIST_REQUEST";
export const OLEVEL_UPLOAD_LIST_MY_SUCCESS = "OLEVEL_UPLOAD_LIST_SUCCESS";
export const OLEVEL_UPLOAD_LIST_MY_FAIL = "OLEVEL_UPLOAD_LIST_FAIL";

export const OLEVEL_UPLOAD_DETAILS_REQUEST = "OLEVEL_UPLOAD_DETAILS_REQUEST";
export const OLEVEL_UPLOAD_DETAILS_SUCCESS = "OLEVEL_UPLOAD_DETAILS_SUCCESS";
export const OLEVEL_UPLOAD_DETAILS_FAIL = "OLEVEL_UPLOAD_DETAILS_FAIL";

export const OLEVEL_UPLOAD_DELETE_REQUEST = "OLEVEL_UPLOAD_DELETE_REQUEST";
export const OLEVEL_UPLOAD_DELETE_SUCCESS = "OLEVEL_UPLOAD_DELETE_SUCCESS";
export const OLEVEL_UPLOAD_DELETE_FAIL = "OLEVEL_UPLOAD_DELETE_FAIL";

export const OLEVEL_UPLOAD_CREATE_REQUEST = "OLEVEL_UPLOAD_CREATE_REQUEST";
export const OLEVEL_UPLOAD_CREATE_SUCCESS = "OLEVEL_UPLOAD_CREATE_SUCCESS";
export const OLEVEL_UPLOAD_CREATE_FAIL = "OLEVEL_UPLOAD_CREATE_FAIL";
export const OLEVEL_UPLOAD_CREATE_RESET = "OLEVEL_UPLOAD_CREATE_RESET";

export const OLEVEL_UPLOAD_UPDATE_REQUEST = "OLEVEL_UPLOAD_UPDATE_REQUEST";
export const OLEVEL_UPLOAD_UPDATE_SUCCESS = "OLEVEL_UPLOAD_UPDATE_SUCCESS";
export const OLEVEL_UPLOAD_UPDATE_FAIL = "OLEVEL_UPLOAD_UPDATE_FAIL";

export const OLEVEL_UPLOAD_ITEM_DELIVER_REQUEST = "OLEVEL_UPLOAD_ITEM_DELIVER_REQUEST";
export const OLEVEL_UPLOAD_ITEM_DELIVER_SUCCESS = "OLEVEL_UPLOAD_ITEM_DELIVER_SUCCESS";
export const OLEVEL_UPLOAD_ITEM_DELIVER_FAIL = "OLEVEL_UPLOAD_ITEM_DELIVER_FAIL";