export const SOLD_CARD_CREATE_REQUEST = 'SOLD_CARD_CREATE_REQUEST'
export const SOLD_CARD_CREATE_SUCCESS = 'SOLD_CARD_CREATE_SUCCESS'
export const SOLD_CARD_CREATE_FAIL = 'SOLD_CARD_CREATE_FAIL'

export const CARD_MY_REQUEST = "CARD_MY_REQUEST";
export const CARD_MY_SUCCESS = "CARD_MY_SUCCESS";
export const CARD_MY_FAIL = "CARD_MY_FAIL";