export const SUBJECT_CREATE_REQUEST = "SUBJECT_CREATE_REQUEST";
export const SUBJECT_CREATE_SUCCESS = "SUBJECT_CREATE_SUCCESS";
export const SUBJECT_CREATE_FAIL = "SUBJECT_CREATE_FAIL";

export const SUBJECT_LIST_REQUEST = "SUBJECT_LIST_REQUEST";
export const SUBJECT_LIST_SUCCESS = "SUBJECT_LIST_SUCCESS";
export const SUBJECT_LIST_FAIL = "SUBJECT_LIST_FAIL";