export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const USER_CONFIRM_EMAIL_REQUEST = 'USER_CONFIRM_EMAIL_REQUEST'
export const USER_CONFIRM_EMAIL_SUCCESS = 'USER_CONFIRM_EMAIL_SUCCESS'
export const USER_CONFIRM_EMAIL_FAIL = 'USER_CONFIRM_EMAIL_FAIL'

export const USER_RESEND_CODE_REQUEST = 'USER_RESEND_CODE_REQUEST'
export const USER_RESEND_CODE_SUCCESS = 'USER_RESEND_CODE_SUCCESS'
export const USER_RESEND_CODE_FAIL = 'USER_RESEND_CODE_FAIL'

export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST'
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS'
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL'

export const USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST'
export const USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS'
export const USER_PASSWORD_RESET_FAIL = 'USER_PASSWORD_RESET_FAIL'

export const USER_PROFILE_PHOTO_REQUEST = 'USER_PROFILE_PHOTO_REQUEST'
export const USER_PROFILE_PHOTO_SUCCESS = 'USER_PROFILE_PHOTO_SUCCESS'
export const USER_PROFILE_PHOTO_FAIL = 'USER_PROFILE_PHOTO_FAIL'

export const WALLET_DEBIT_REQUEST = 'WALLET_DEBIT_REQUEST'
export const WALLET_DEBIT_SUCCESS = 'WALLET_DEBIT_SUCCESS'
export const WALLET_DEBIT_FAIL = 'WALLET_DEBIT_FAIL'

export const WALLET_CREDIT_REQUEST = 'WALLET_CREDIT_REQUEST'
export const WALLET_CREDIT_SUCCESS = 'WALLET_CREDIT_SUCCESS'
export const WALLET_CREDIT_FAIL = 'WALLET_CREDIT_FAIL'

export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE'

export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST'
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS'
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL'

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_MAKEADMIN_REQUEST = 'USER_MAKEADMIN_REQUEST'
export const USER_MAKEADMIN_SUCCESS = 'USER_MAKEADMIN_SUCCESS'
export const USER_MAKEADMIN_FAIL = 'USER_MAKEADMIN_FAIL'

export const USER_EMAIL_REQUEST = 'USER_EMAIL_REQUEST'
export const USER_EMAIL_SUCCESS = 'USER_EMAIL_SUCCESS'
export const USER_EMAIL_FAIL = 'USER_EMAIL_FAIL'

export const USERS_EMAIL_REQUEST = 'USERS_EMAIL_REQUEST'
export const USERS_EMAIL_SUCCESS = 'USERS_EMAIL_SUCCESS'
export const USERS_EMAIL_FAIL = 'USERS_EMAIL_FAIL'